/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atminterface.gui;

import atminterface.Dao.AccountDao;
import atminterface.Dao.TransDao;
import atminterface.Pojo.TranshistoryPojo;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class TransferFrame extends javax.swing.JFrame {

    /**
     * Creates new form TransferFrame
     */
     private TranshistoryPojo th;
    private int oldBalanceOf1,oldBalanceOf2,account_no,amount;
    public TransferFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
      private int deptNo;
    public TransferFrame(int accNo){
        this();
        deptNo = accNo;
        lblAccNo.setText(deptNo+"");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAccNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnCheckAccountNo = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccNo.setEditable(false);
        lblAccNo.setBackground(new java.awt.Color(0, 0, 0));
        lblAccNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAccNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Account No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/atm/free3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, 513));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Welcome to Bandhan Bank");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 497, 35));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfer Money", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Account No:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Amount");

        txtAccountNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnCheckAccountNo.setBackground(new java.awt.Color(204, 204, 204));
        btnCheckAccountNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckAccountNo.setText("Check Account No");
        btnCheckAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAccountNoActionPerformed(evt);
            }
        });

        btnTransfer.setBackground(new java.awt.Color(204, 204, 204));
        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAccountNo)
                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnCheckAccountNo)
                .addGap(112, 112, 112)
                .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAccountNo)
                    .addComponent(btnTransfer)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 568, 976, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
         try{ 
           
            boolean res = AccountDao.withdrawbalance(deptNo, amount, oldBalanceOf1);
            boolean res1 = AccountDao.depositeBalance(account_no, amount, oldBalanceOf2);
            if(res == true && res1 == true){
                JOptionPane.showMessageDialog(null,"Money debited");
                int acc = deptNo;
            String status = "transfer(debited)";
            int amt = Integer.parseInt(txtAmount.getText().trim());
            LocalDateTime today = LocalDateTime.now();
            DateTimeFormatter obj = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
            String date = today.format(obj);
            th = new TranshistoryPojo();
            th.setAcc_no(acc);
            th.setTransDate(date);
            th.setAmount(amt);
            th.setStatus(status);
            boolean result1 = TransDao.SaveHistory(th);
            int acc1 = account_no;
            String status1 = "transfer(credited)";
             amt = Integer.parseInt(txtAmount.getText().trim());

            LocalDateTime today1 = LocalDateTime.now();
            DateTimeFormatter obj1 = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
            String date1 = today.format(obj1);
            th = new TranshistoryPojo();
            th.setAcc_no(acc1);
            th.setTransDate(date1);
            th.setAmount(amt);
            th.setStatus(status1);
            boolean result2 = TransDao.SaveHistory(th);
                loadBalance();
                clear();
                return;
            }
            JOptionPane.showMessageDialog(null,"Money can't debited.Try again!!");
        }
        catch(SQLException rs){
            JOptionPane.showMessageDialog(null,"Error in DB");
            rs.printStackTrace();
        }
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnCheckAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAccountNoActionPerformed
         if(!validateInput()){
            JOptionPane.showMessageDialog(null,"Please input all data");
            return;
        }
         account_no = Integer.parseInt(txtAccountNo.getText().trim());
         amount = Integer.parseInt(txtAmount.getText().trim());
        try{
           String nameofCreditor  = AccountDao.getAccountDetailsByAccno(account_no);
            if(nameofCreditor != null){
                JOptionPane.showMessageDialog(null,"You can transfer. Valid account no." );
                 loadBalance();
            if(amount > oldBalanceOf1){
            JOptionPane.showMessageDialog(null,"You don't have sufficient balance");
            return;
            }
             btnTransfer.setEnabled(true);
                
              // JOptionPane.showMessageDialog(null,"found Account No,Try again!!" );
            }
            else
            JOptionPane.showMessageDialog(null,"Please enter valid acc no" );
        }
        catch(SQLException rs){
            JOptionPane.showMessageDialog(null,"Error in DB");
            rs.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnCheckAccountNoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       MainMenueFrame mf = new MainMenueFrame(deptNo);
       mf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAccountNo;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lblAccNo;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables

    private void loadBalance() {
      try{
        oldBalanceOf1 = AccountDao.getBalance(deptNo);
        oldBalanceOf2 = AccountDao.getBalance(Integer.parseInt(txtAccountNo.getText().trim()));
    } catch(SQLException es){
            JOptionPane.showMessageDialog(null,"Error in DB");
            es.printStackTrace();
            
        }
    }

    private void clear() {
       txtAccountNo.setText("");
       txtAmount.setText("");
    }

    private boolean validateInput() {
       if(txtAccountNo.getText().isEmpty() || txtAmount.getText().isEmpty())
            return false;
            return true;
    }
}
